version: '3'

networks:
    web:
        external: true

services:
    influxdb:
        image: influxdb:1.8-alpine
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - ${DATA_ROOT_DIR:-/srv/data}/tiltapi/influxdb:/var/lib/influxdb

    grafana:
        image: grafana/grafana:latest
        restart: unless-stopped
        # ports:
            # - "3000:3000"
        volumes:
            - ${DATA_ROOT_DIR:-/srv/data}/tiltapi/grafana:/var/lib/grafana
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.grafana.rule=Host(`grafana.kenh.fr`,`grafana.ananas.space`)"
            - "traefik.http.services.grafana.loadbalancer.server.port=3000"
        networks:
            - web
            - default

    api:
        build: .
        restart: unless-stopped
        # ports:
            # - "1234:1234"
        env_file:
            - .env
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.tiltapi.rule=Host(`tiltapi.kenh.fr`,`tiltapi.ananas.space`)"
            - "traefik.http.services.tiltapi.loadbalancer.server.port=1234"
        networks:
            - web
            - default
